// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBase.proto

package com.maihe.proto.DataBase;

public final class DataBase {
  private DataBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataBase_DBRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataBase_DBRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataBase_DBResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataBase_DBResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataBase_SQLRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataBase_SQLRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataBase_SQLResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataBase_SQLResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DataBase.proto\022\010DataBase\"\013\n\tDBRequest\"" +
      "\034\n\nDBResponse\022\016\n\006result\030\001 \001(\t\"\031\n\nSQLRequ" +
      "est\022\013\n\003sql\030\001 \001(\t\"\035\n\013SQLResponse\022\016\n\006resul" +
      "t\030\001 \001(\t2\257\001\n\006DBInfo\0226\n\007getPros\022\023.DataBase" +
      ".DBRequest\032\024.DataBase.DBResponse\"\000\0226\n\005qu" +
      "ery\022\024.DataBase.SQLRequest\032\025.DataBase.SQL" +
      "Response\"\000\0225\n\004edit\022\024.DataBase.SQLRequest" +
      "\032\025.DataBase.SQLResponse\"\000B+\n\030com.maihe.p" +
      "roto.DataBaseB\010DataBaseP\001\242\002\002MHb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DataBase_DBRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataBase_DBRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataBase_DBRequest_descriptor,
        new java.lang.String[] { });
    internal_static_DataBase_DBResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataBase_DBResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataBase_DBResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_DataBase_SQLRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DataBase_SQLRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataBase_SQLRequest_descriptor,
        new java.lang.String[] { "Sql", });
    internal_static_DataBase_SQLResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DataBase_SQLResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataBase_SQLResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
