// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBase.proto

package com.maihe.proto.DataBase;

public interface DBRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataBase.DBRequest)
    com.google.protobuf.MessageOrBuilder {
}
