// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBase.proto

package com.maihe.proto.DataBase;

public interface SQLRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataBase.SQLRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sql = 1;</code>
   */
  java.lang.String getSql();
  /**
   * <code>string sql = 1;</code>
   */
  com.google.protobuf.ByteString
      getSqlBytes();
}
