// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBase.proto

package com.maihe.proto.DataBase;

public interface SQLResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataBase.SQLResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
