// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Excel.proto

package com.maihe.proto.Excel;

public interface excelParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Excel.excelParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string excelName = 1;</code>
   */
  java.lang.String getExcelName();
  /**
   * <code>string excelName = 1;</code>
   */
  com.google.protobuf.ByteString
      getExcelNameBytes();

  /**
   * <code>string excelRoute = 2;</code>
   */
  java.lang.String getExcelRoute();
  /**
   * <code>string excelRoute = 2;</code>
   */
  com.google.protobuf.ByteString
      getExcelRouteBytes();

  /**
   * <code>string excelHead = 3;</code>
   */
  java.lang.String getExcelHead();
  /**
   * <code>string excelHead = 3;</code>
   */
  com.google.protobuf.ByteString
      getExcelHeadBytes();

  /**
   * <code>string excelData = 4;</code>
   */
  java.lang.String getExcelData();
  /**
   * <code>string excelData = 4;</code>
   */
  com.google.protobuf.ByteString
      getExcelDataBytes();
}
