// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Excel.proto

package com.maihe.proto.Excel;

public final class Excel {
  private Excel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Excel_excelParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Excel_excelParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Excel_excelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Excel_excelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Excel.proto\022\005Excel\"Z\n\013excelParams\022\021\n\te" +
      "xcelName\030\001 \001(\t\022\022\n\nexcelRoute\030\002 \001(\t\022\021\n\tex" +
      "celHead\030\003 \001(\t\022\021\n\texcelData\030\004 \001(\t\"\037\n\rexce" +
      "lResponse\022\016\n\006result\030\001 \001(\t2F\n\014ExcelServic" +
      "e\0226\n\010genExcel\022\022.Excel.excelParams\032\024.Exce" +
      "l.excelResponse\"\000B%\n\025com.maihe.proto.Exc" +
      "elB\005ExcelP\001\242\002\002MHb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Excel_excelParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Excel_excelParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Excel_excelParams_descriptor,
        new java.lang.String[] { "ExcelName", "ExcelRoute", "ExcelHead", "ExcelData", });
    internal_static_Excel_excelResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Excel_excelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Excel_excelResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
