// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Excel.proto

package com.maihe.proto.Excel;

public interface excelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Excel.excelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
