// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Excel.proto

package com.maihe.proto.Excel;

/**
 * Protobuf type {@code Excel.excelParams}
 */
public  final class excelParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Excel.excelParams)
    excelParamsOrBuilder {
  // Use excelParams.newBuilder() to construct.
  private excelParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private excelParams() {
    excelName_ = "";
    excelRoute_ = "";
    excelHead_ = "";
    excelData_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private excelParams(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            excelName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            excelRoute_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            excelHead_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            excelData_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.maihe.proto.Excel.Excel.internal_static_Excel_excelParams_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.maihe.proto.Excel.Excel.internal_static_Excel_excelParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.maihe.proto.Excel.excelParams.class, com.maihe.proto.Excel.excelParams.Builder.class);
  }

  public static final int EXCELNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object excelName_;
  /**
   * <code>string excelName = 1;</code>
   */
  public java.lang.String getExcelName() {
    java.lang.Object ref = excelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      excelName_ = s;
      return s;
    }
  }
  /**
   * <code>string excelName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getExcelNameBytes() {
    java.lang.Object ref = excelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      excelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCELROUTE_FIELD_NUMBER = 2;
  private volatile java.lang.Object excelRoute_;
  /**
   * <code>string excelRoute = 2;</code>
   */
  public java.lang.String getExcelRoute() {
    java.lang.Object ref = excelRoute_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      excelRoute_ = s;
      return s;
    }
  }
  /**
   * <code>string excelRoute = 2;</code>
   */
  public com.google.protobuf.ByteString
      getExcelRouteBytes() {
    java.lang.Object ref = excelRoute_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      excelRoute_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCELHEAD_FIELD_NUMBER = 3;
  private volatile java.lang.Object excelHead_;
  /**
   * <code>string excelHead = 3;</code>
   */
  public java.lang.String getExcelHead() {
    java.lang.Object ref = excelHead_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      excelHead_ = s;
      return s;
    }
  }
  /**
   * <code>string excelHead = 3;</code>
   */
  public com.google.protobuf.ByteString
      getExcelHeadBytes() {
    java.lang.Object ref = excelHead_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      excelHead_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXCELDATA_FIELD_NUMBER = 4;
  private volatile java.lang.Object excelData_;
  /**
   * <code>string excelData = 4;</code>
   */
  public java.lang.String getExcelData() {
    java.lang.Object ref = excelData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      excelData_ = s;
      return s;
    }
  }
  /**
   * <code>string excelData = 4;</code>
   */
  public com.google.protobuf.ByteString
      getExcelDataBytes() {
    java.lang.Object ref = excelData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      excelData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getExcelNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, excelName_);
    }
    if (!getExcelRouteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, excelRoute_);
    }
    if (!getExcelHeadBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, excelHead_);
    }
    if (!getExcelDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, excelData_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getExcelNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, excelName_);
    }
    if (!getExcelRouteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, excelRoute_);
    }
    if (!getExcelHeadBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, excelHead_);
    }
    if (!getExcelDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, excelData_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.maihe.proto.Excel.excelParams)) {
      return super.equals(obj);
    }
    com.maihe.proto.Excel.excelParams other = (com.maihe.proto.Excel.excelParams) obj;

    boolean result = true;
    result = result && getExcelName()
        .equals(other.getExcelName());
    result = result && getExcelRoute()
        .equals(other.getExcelRoute());
    result = result && getExcelHead()
        .equals(other.getExcelHead());
    result = result && getExcelData()
        .equals(other.getExcelData());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXCELNAME_FIELD_NUMBER;
    hash = (53 * hash) + getExcelName().hashCode();
    hash = (37 * hash) + EXCELROUTE_FIELD_NUMBER;
    hash = (53 * hash) + getExcelRoute().hashCode();
    hash = (37 * hash) + EXCELHEAD_FIELD_NUMBER;
    hash = (53 * hash) + getExcelHead().hashCode();
    hash = (37 * hash) + EXCELDATA_FIELD_NUMBER;
    hash = (53 * hash) + getExcelData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.maihe.proto.Excel.excelParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.maihe.proto.Excel.excelParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.maihe.proto.Excel.excelParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.maihe.proto.Excel.excelParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.maihe.proto.Excel.excelParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Excel.excelParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Excel.excelParams)
      com.maihe.proto.Excel.excelParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.maihe.proto.Excel.Excel.internal_static_Excel_excelParams_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.maihe.proto.Excel.Excel.internal_static_Excel_excelParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.maihe.proto.Excel.excelParams.class, com.maihe.proto.Excel.excelParams.Builder.class);
    }

    // Construct using com.maihe.proto.Excel.excelParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      excelName_ = "";

      excelRoute_ = "";

      excelHead_ = "";

      excelData_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.maihe.proto.Excel.Excel.internal_static_Excel_excelParams_descriptor;
    }

    public com.maihe.proto.Excel.excelParams getDefaultInstanceForType() {
      return com.maihe.proto.Excel.excelParams.getDefaultInstance();
    }

    public com.maihe.proto.Excel.excelParams build() {
      com.maihe.proto.Excel.excelParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.maihe.proto.Excel.excelParams buildPartial() {
      com.maihe.proto.Excel.excelParams result = new com.maihe.proto.Excel.excelParams(this);
      result.excelName_ = excelName_;
      result.excelRoute_ = excelRoute_;
      result.excelHead_ = excelHead_;
      result.excelData_ = excelData_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.maihe.proto.Excel.excelParams) {
        return mergeFrom((com.maihe.proto.Excel.excelParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.maihe.proto.Excel.excelParams other) {
      if (other == com.maihe.proto.Excel.excelParams.getDefaultInstance()) return this;
      if (!other.getExcelName().isEmpty()) {
        excelName_ = other.excelName_;
        onChanged();
      }
      if (!other.getExcelRoute().isEmpty()) {
        excelRoute_ = other.excelRoute_;
        onChanged();
      }
      if (!other.getExcelHead().isEmpty()) {
        excelHead_ = other.excelHead_;
        onChanged();
      }
      if (!other.getExcelData().isEmpty()) {
        excelData_ = other.excelData_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.maihe.proto.Excel.excelParams parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.maihe.proto.Excel.excelParams) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object excelName_ = "";
    /**
     * <code>string excelName = 1;</code>
     */
    public java.lang.String getExcelName() {
      java.lang.Object ref = excelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string excelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExcelNameBytes() {
      java.lang.Object ref = excelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string excelName = 1;</code>
     */
    public Builder setExcelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      excelName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string excelName = 1;</code>
     */
    public Builder clearExcelName() {
      
      excelName_ = getDefaultInstance().getExcelName();
      onChanged();
      return this;
    }
    /**
     * <code>string excelName = 1;</code>
     */
    public Builder setExcelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      excelName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object excelRoute_ = "";
    /**
     * <code>string excelRoute = 2;</code>
     */
    public java.lang.String getExcelRoute() {
      java.lang.Object ref = excelRoute_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excelRoute_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string excelRoute = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExcelRouteBytes() {
      java.lang.Object ref = excelRoute_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excelRoute_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string excelRoute = 2;</code>
     */
    public Builder setExcelRoute(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      excelRoute_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string excelRoute = 2;</code>
     */
    public Builder clearExcelRoute() {
      
      excelRoute_ = getDefaultInstance().getExcelRoute();
      onChanged();
      return this;
    }
    /**
     * <code>string excelRoute = 2;</code>
     */
    public Builder setExcelRouteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      excelRoute_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object excelHead_ = "";
    /**
     * <code>string excelHead = 3;</code>
     */
    public java.lang.String getExcelHead() {
      java.lang.Object ref = excelHead_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excelHead_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string excelHead = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExcelHeadBytes() {
      java.lang.Object ref = excelHead_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excelHead_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string excelHead = 3;</code>
     */
    public Builder setExcelHead(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      excelHead_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string excelHead = 3;</code>
     */
    public Builder clearExcelHead() {
      
      excelHead_ = getDefaultInstance().getExcelHead();
      onChanged();
      return this;
    }
    /**
     * <code>string excelHead = 3;</code>
     */
    public Builder setExcelHeadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      excelHead_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object excelData_ = "";
    /**
     * <code>string excelData = 4;</code>
     */
    public java.lang.String getExcelData() {
      java.lang.Object ref = excelData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excelData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string excelData = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExcelDataBytes() {
      java.lang.Object ref = excelData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        excelData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string excelData = 4;</code>
     */
    public Builder setExcelData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      excelData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string excelData = 4;</code>
     */
    public Builder clearExcelData() {
      
      excelData_ = getDefaultInstance().getExcelData();
      onChanged();
      return this;
    }
    /**
     * <code>string excelData = 4;</code>
     */
    public Builder setExcelDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      excelData_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Excel.excelParams)
  }

  // @@protoc_insertion_point(class_scope:Excel.excelParams)
  private static final com.maihe.proto.Excel.excelParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.maihe.proto.Excel.excelParams();
  }

  public static com.maihe.proto.Excel.excelParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<excelParams>
      PARSER = new com.google.protobuf.AbstractParser<excelParams>() {
    public excelParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new excelParams(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<excelParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<excelParams> getParserForType() {
    return PARSER;
  }

  public com.maihe.proto.Excel.excelParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

