// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InputData.proto

package com.maihe.proto.InputData;

public final class Excel {
  private Excel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InputDataPackage_inputDataMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InputDataPackage_inputDataMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InputDataPackage_inputDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InputDataPackage_inputDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017InputData.proto\022\020InputDataPackage\"(\n\020i" +
      "nputDataMessage\022\024\n\014inputDataSql\030\001 \001(\t\"#\n" +
      "\021inputDataResponse\022\016\n\006result\030\001 \001(\t2j\n\020In" +
      "putDataService\022V\n\tinputData\022\".InputDataP" +
      "ackage.inputDataMessage\032#.InputDataPacka" +
      "ge.inputDataResponse\"\000B)\n\031com.maihe.prot" +
      "o.InputDataB\005ExcelP\001\242\002\002MHb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InputDataPackage_inputDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InputDataPackage_inputDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InputDataPackage_inputDataMessage_descriptor,
        new java.lang.String[] { "InputDataSql", });
    internal_static_InputDataPackage_inputDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InputDataPackage_inputDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InputDataPackage_inputDataResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
