// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InputData.proto

package com.maihe.proto.InputData;

public interface inputDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InputDataPackage.inputDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
