// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.maihe.proto.User;

public interface ResultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User.ResultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
