// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.maihe.proto.User;

public final class TokenProto {
  private TokenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_UserNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_UserNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_ResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_ResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\004User\"#\n\017UserNameRequest\022\020\n" +
      "\010username\030\001 \001(\t\"2\n\014UserResponse\022\020\n\010usern" +
      "ame\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"1\n\013UserReque" +
      "st\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"!" +
      "\n\016ResultResponse\022\017\n\007success\030\001 \001(\0102}\n\004Use" +
      "r\0229\n\014saveUserInfo\022\021.User.UserRequest\032\024.U" +
      "ser.ResultResponse\"\000\022:\n\013getUserInfo\022\025.Us" +
      "er.UserNameRequest\032\022.User.UserResponse\"\000" +
      "B*\n\024com.maihe.proto.UserB\nTokenProtoP\001\242\002" +
      "\003TKPb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_UserNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_UserNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_UserNameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_User_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_UserResponse_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_User_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_User_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_UserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_User_ResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_User_ResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_ResultResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
