// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.maihe.proto.User;

public interface UserNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User.UserNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
