// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.maihe.proto.User;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
